### ISSUE TITLE
Materials not licensed for re-distribution

### ISSUE THREAD

**Issue by ffund** [AgainstEntropy/ECE-GY-6143-ML#1]
Hi! The "notebooks" directory you have shared here is material that is not licensed under an open source license, so you are not permitted to redistribute them (e.g. post them online or in your own repo). 

Would you please remove that directory? 

Thank you!
ffund

**Comment by AgainstEntropy** [comment]
> Hi! The "notebooks" directory you have shared here is material that is not licensed under an open source license, so you are not permitted to redistribute them (e.g. post them online or in your own repo).
> 
> Would you please remove that directory?
> 
> Thank you! ffund

Hi Professor! I'm very sorry for uploading the notebooks😢 I have removed them.

**Comment by ffund** [comment]
Thanks a lot, I appreciate the prompt response :smile:
